name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  unittest:
    strategy:
      matrix:
        go-version: [1.17, 1.18, 1.19, 1.20]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build Go ${{ matrix.go }}
        run: go build -v ./...
      - name: Test Go ${{ matrix.go }}
        run: go test  ./... -v

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

